apiVersion: cosmos.strange.love/v1
kind: CosmosFullNode
metadata:
  name: cosmoshub-test
  namespace: nnw-dev
spec:
  chain:
    app:
      minGasPrice: 0.001uatom
    binary: gaiad
    chainID: cosmoshub-4
    config:
      seeds: ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:14956 # TODO
    genesisURL: https://snapshots.polkachu.com/genesis/cosmos/genesis.json
    network: mainnet
    skipInvariants: true
    snapshotURL: https://snapshots.polkachu.com/snapshots/cosmos/cosmos_15032348.tar.lz4 # TODO
  podTemplate:
    image: ghcr.io/strangelove-ventures/heighliner/gaia:v0.46.12 # TODO
    resources:
      requests:
        memory: 4Gi
  replicas: 1 # TODO change to 1 to use less resources
  volumeClaimTemplate:
    resources:
      requests:
        storage: 10Gi
    storageClassName: hostpath # TODO
